#!/bin/bash
# =============================================================================
# Generate Docker Compose Override for Service Networks
# =============================================================================
# Copyright (C) 2024-2026 David Kleinhans, Jade University of Applied Sciences
# SPDX-License-Identifier: Apache-2.0
# =============================================================================
# This script reads SERVICE_* variables from .env and generates a
# docker-compose.override.yml file that adds the required external networks
# to the nginx service. If LETSENCRYPT_ENABLED=true, it also includes the
# certbot service and shared volumes for automated certificate management.
#
# WHEN TO RUN THIS SCRIPT:
#   - After adding, removing, or changing services in .env
#   - After changing LETSENCRYPT_ENABLED in .env
#   - After initial setup (configure-env.sh runs it automatically)
#   Note: init-letsencrypt.sh will call this script automatically if needed.
#
# Usage:
#   ./scripts/generate-compose-override.sh
#
# The generated file is automatically used by docker compose.
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# =============================================================================
# Main Script
# =============================================================================

echo ""
log_info "=========================================="
log_info "Generating docker-compose.override.yml"
log_info "=========================================="
echo ""

# Check if .env exists
if [ ! -f .env ]; then
    log_error ".env file not found!"
    log_info "Run ./scripts/configure-env.sh first to create .env"
    exit 1
fi

# Source .env to get SERVICE_* variables
set -a
source .env
set +a

# Collect enabled service networks and access restrictions
declare -a networks
declare -a restricted_services  # names of services needing a dedicated proxy
service_count=0

for i in $(seq 1 99); do
    name_var="SERVICE_${i}_NAME"
    enabled_var="SERVICE_${i}_ENABLED"
    network_var="SERVICE_${i}_NETWORK"
    allowed_email_domain_var="SERVICE_${i}_ALLOWED_EMAIL_DOMAIN"
    allowed_group_var="SERVICE_${i}_ALLOWED_GROUP"
    
    eval name="\${$name_var:-}"
    eval enabled="\${$enabled_var:-true}"
    eval network="\${$network_var:-}"
    eval allowed_email_domain="\${$allowed_email_domain_var:-}"
    eval allowed_group="\${$allowed_group_var:-}"
    
    # Stop if no more services defined
    [ -z "$name" ] && break
    
    # Skip disabled services
    if [ "$enabled" != "true" ]; then
        log_info "Skipping disabled service: $name"
        continue
    fi
    
    # Add network if defined
    if [ -n "$network" ]; then
        # Check if network is already in array (avoid duplicates)
        if [[ ! " ${networks[*]} " =~ " ${network} " ]]; then
            networks+=("$network")
            log_info "Adding network: $network (for $name)"
        fi
    fi
    
    # Track services that need a dedicated oauth2-proxy
    if [ -n "$allowed_email_domain" ] || [ -n "$allowed_group" ]; then
        restricted_services+=("$i:$name:$allowed_email_domain:$allowed_group")
        log_info "Access restriction for $name: email_domain='${allowed_email_domain:-*}' group='${allowed_group:-(none)}'"
    fi
    
    service_count=$((service_count + 1))
done

# Generate docker-compose.override.yml
OUTPUT_FILE="docker-compose.override.yml"

if [ ${#networks[@]} -eq 0 ]; then
    log_warn "No services with networks configured"
    log_info "Removing existing override file (if any)"
    rm -f "$OUTPUT_FILE"
    echo ""
    log_info "No docker-compose.override.yml needed"
    exit 0
fi

log_info "Generating $OUTPUT_FILE..."

# --- Check if Let's Encrypt is enabled ---
LE_ENABLED="${LETSENCRYPT_ENABLED:-false}"
if [ "$LE_ENABLED" = "true" ]; then
    log_info "Let's Encrypt is ENABLED — including certbot service and volumes"
fi

cat > "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# Docker Compose Override - Service Networks & Let's Encrypt
# =============================================================================
# AUTO-GENERATED by ./scripts/generate-compose-override.sh
# DO NOT EDIT MANUALLY - regenerate with the script after changing .env
# =============================================================================

services:
  nginx:
    networks:
EOF

# Add each network to nginx service
for network in "${networks[@]}"; do
    echo "      - $network" >> "$OUTPUT_FILE"
done

# --- Let's Encrypt: add nginx volume overrides and certbot dependency ---
if [ "$LE_ENABLED" = "true" ]; then
    cat >> "$OUTPUT_FILE" << 'EOF'
    volumes:
      # Override certificate mount to use Let's Encrypt directory structure
      - certbot_certs:/etc/letsencrypt:ro
      # Webroot for ACME HTTP-01 challenge
      - certbot_webroot:/var/www/certbot:ro
    depends_on:
      - certbot

  # ---------------------------------------------------------------------------
  # Certbot - Automated certificate issuance & renewal
  # ---------------------------------------------------------------------------
  certbot:
    image: certbot/certbot:latest
    container_name: edge_certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot --quiet; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
      - certbot_logs:/var/log/letsencrypt
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
EOF
fi

# --- Per-service restricted oauth2-proxy instances ---
# Each Pattern B service with ALLOWED_EMAIL_DOMAIN or ALLOWED_GROUP gets its
# own oauth2-proxy container so it can enforce per-service access rules.
#
# IMPORTANT: The command flags below mirror the base edge_oauth2_proxy definition
# in docker-compose.yml. If you update the base proxy flags (e.g. to add scopes,
# change PKCE method, etc.), you must update this block as well.
if [ ${#restricted_services[@]} -gt 0 ]; then
    for entry in "${restricted_services[@]}"; do
        IFS=':' read -r svc_i svc_name svc_email_domain svc_group <<< "$entry"
        
        log_info "Generating dedicated oauth2-proxy for: $svc_name"
        
        # Build restriction flags
        restriction_flags=""
        if [ -n "$svc_email_domain" ]; then
            restriction_flags="${restriction_flags}\n      - --email-domain=${svc_email_domain}"
        else
            restriction_flags="${restriction_flags}\n      - --email-domain=*"
        fi
        if [ -n "$svc_group" ]; then
            # Keycloak group paths require a leading slash
            restriction_flags="${restriction_flags}\n      - --allowed-group=/${svc_group}"
        fi
        
        cat >> "$OUTPUT_FILE" << EOF

  # ---------------------------------------------------------------------------
  # Dedicated oauth2-proxy for: $svc_name
  # Restrictions: email_domain='${svc_email_domain:-*}'  group='${svc_group:-(none)}'
  # ---------------------------------------------------------------------------
  oauth2-proxy-${svc_name}:
    image: quay.io/oauth2-proxy/oauth2-proxy:\${OAUTH2_PROXY_VERSION:-v7.6.0}
    container_name: edge_oauth2_proxy_${svc_name}
    restart: unless-stopped
    command:
      - --http-address=0.0.0.0:4180
      - --upstream=static://202
      - --cookie-secure=true
      - --cookie-domain=\${OAUTH2_PROXY_COOKIE_DOMAIN:-.example.org}
      - --whitelist-domain=\${OAUTH2_PROXY_COOKIE_DOMAIN:-.example.org}
      - --provider=oidc
      - --provider-display-name=Keycloak
      - --scope=openid email profile
      - --oidc-email-claim=email
      - --oidc-groups-claim=groups
      - --oidc-issuer-url=http://keycloak:8080/realms/\${KEYCLOAK_REALM:-master}
      - --redirect-url=https://\${DOMAIN_AUTH:-auth.example.org}/oauth2/callback
      - --reverse-proxy=true
      - --set-xauthrequest=true
      - --pass-user-headers=true
      - --pass-access-token=true
      - --pass-authorization-header=true
      - --set-authorization-header=true
      - --skip-provider-button=true
      - --insecure-oidc-skip-issuer-verification=true
      - --ssl-insecure-skip-verify=true
      - --insecure-oidc-allow-unverified-email=true
      - --skip-claims-from-profile-url=true
      - --code-challenge-method=S256$(printf "%b" "$restriction_flags")
    environment:
      OAUTH2_PROXY_CLIENT_ID: \${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: \${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: \${OAUTH2_PROXY_COOKIE_SECRET}
    networks:
      - auth_backend
    depends_on:
      keycloak:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
EOF
    done
fi

# Add networks section
cat >> "$OUTPUT_FILE" << 'EOF'

networks:
EOF

# Define each external network
for network in "${networks[@]}"; do
    cat >> "$OUTPUT_FILE" << EOF
  $network:
    external: true
EOF
done

# auth_backend is needed by any dedicated oauth2-proxy instance.
# It is defined in docker-compose.yml so we just reference it here.
if [ ${#restricted_services[@]} -gt 0 ]; then
    cat >> "$OUTPUT_FILE" << 'EOF'
  auth_backend:
    external: false
EOF
fi

# --- Let's Encrypt: add volume definitions ---
if [ "$LE_ENABLED" = "true" ]; then
    cat >> "$OUTPUT_FILE" << 'EOF'

volumes:
  certbot_certs:
    driver: local
  certbot_webroot:
    driver: local
  certbot_logs:
    driver: local
EOF
fi

echo ""
log_info "=========================================="
log_info "Generated: $OUTPUT_FILE"
log_info "=========================================="
echo ""
log_info "Configured $service_count service(s) with ${#networks[@]} network(s):"
for network in "${networks[@]}"; do
    log_info "  - $network"
done
if [ ${#restricted_services[@]} -gt 0 ]; then
    log_info "Dedicated oauth2-proxy instances: ${#restricted_services[@]}"
    for entry in "${restricted_services[@]}"; do
        IFS=':' read -r svc_i svc_name svc_email_domain svc_group <<< "$entry"
        log_info "  - oauth2-proxy-${svc_name}  (email_domain='${svc_email_domain:-*}'  group='${svc_group:-(none)}')"
    done
fi
if [ "$LE_ENABLED" = "true" ]; then
    log_info "Let's Encrypt: certbot service and volumes included"
fi
echo ""
log_warn "IMPORTANT: Create these Docker networks before starting:"
for network in "${networks[@]}"; do
    log_warn "  docker network create $network"
done
echo ""
if [ "$LE_ENABLED" = "true" ]; then
    log_info "Let's Encrypt is enabled. To obtain initial certificates:"
    log_info "  ./scripts/init-letsencrypt.sh"
    log_info ""
fi
log_info "Then start the stack:"
log_info "  docker compose up -d"
echo ""

exit 0
